# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-15 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=10, upload_to=b'media/img'),
            preserve_default=False,
        ),
    ]
