# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-19 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20161215_0606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='item_title',
        ),
        migrations.AddField(
            model_name='post',
            name='item_cost',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='seller_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
