# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-19 05:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20161219_0451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='item_title',
            new_name='title',
        ),
    ]
